-- Migration script to update password hashes to Spring Security BCrypt format
-- Password: "pass"
-- Run this after the application has started at least once to ensure BCryptPasswordEncoder is available
-- Or manually generate hash using: new BCryptPasswordEncoder().encode("pass")

-- Option 1: Register new users via API (recommended)
-- POST /api/auth/register with email and password "pass"

-- Option 2: Update existing users (if you have a valid BCrypt hash)
-- Replace HASH_HERE with a BCrypt hash generated by Spring Security
-- UPDATE `users` SET `password_hash` = 'HASH_HERE' WHERE `email` IN ('mary@invoken.com', 'zookeeper@invoken.com');

-- Option 3: Delete and recreate users (if no important data)
-- DELETE FROM `user_roles` WHERE `user_id` IN (SELECT `id` FROM `users` WHERE `email` IN ('mary@invoken.com', 'zookeeper@invoken.com'));
-- DELETE FROM `users` WHERE `email` IN ('mary@invoken.com', 'zookeeper@invoken.com');
-- Then register via API: POST /api/auth/register

